<a href="https://colab.research.google.com/github/TofayelAhamedTopu/Machine_Learning/blob/main/Numpy_Function_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1 Read CSV File
import numpy as np
filename='Data.csv'
data=np.loadtxt(filename,delimiter=',',dtype=str)
print(data)

[['Country' 'Age' 'Salary' 'Purchased']
 ['France' '44' '72000' 'No']
 ['Spain' '27' '48000' 'Yes']
 ['Germany' '30' '54000' 'No']
 ['Spain' '38' '61000' 'No']
 ['Germany' '40' '' 'Yes']
 ['France' '35' '58000' 'Yes']
 ['Spain' '' '52000' 'No']
 ['France' '48' '79000' 'Yes']
 ['Germany' '50' '83000' 'No']
 ['France' '37' '67000' 'Yes']]


In [ ]:
#2 Creating arrays
#Random integers in a specific range
import numpy as np
np.random.randint(5,size=7)

array([4, 1, 4, 0, 2, 0, 2])

In [ ]:
#3 Random floats
np.random.random(5)

array([0.96298522, 0.73504068, 0.57773915, 0.06280542, 0.73953541])

In [ ]:
#4 standard normal distribution mean
print(np.random.random(100).mean())

0.46082120464674103


In [ ]:
#5 standard normal distribution Std
print(np.random.random(100).std())

0.27269567926498545


In [ ]:
#6 Matrix (4,4)
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#7 Matrix (1)
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
#8 Arange fixed Size
np.arange(4)

array([0, 1, 2, 3])

In [ ]:
#9 Arange 
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#10 Transpose switch rows and columns
M=np.random.randint(5,size=(3,4))
M

array([[3, 0, 4, 2],
       [0, 4, 0, 2],
       [3, 3, 1, 3]])

In [ ]:
M.transpose()

array([[3, 0, 3],
       [0, 4, 3],
       [4, 0, 1],
       [2, 2, 3]])

In [ ]:
#11 Concatenate
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.concatenate((a,b))


array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
#12 Vstack arrays vertically
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
z=np.array([9,10,11,12])
np.vstack((x,y,z))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
#13 capitalize
print (np.char.capitalize('hi'))

Hi


In [ ]:
#14 Replace ()

print (np.char.replace ('My Name IS Topu', 'Topu', 'Tofayel'))

My Name IS Tofayel


In [ ]:
#15 lower Case()
print (np.char.lower(['HI','PHYTHON']) )
print (np.char.lower('HELLO'))

['hi' 'phython']
hello


In [ ]:
#16 Upper Case()
print (np.char.upper(['hi','phython']) )
print (np.char.upper('hello'))

['HI' 'PHYTHON']
HELLO


In [ ]:
#17  split()
print (np.char.split ('hello phython?') )

['hello', 'phython?']


In [ ]:
#18 Det Returns the determinant of a matrix
import numpy as np
m=np.random.randint(5,size=(4,4))
m


array([[1, 4, 1, 4],
       [4, 0, 2, 3],
       [4, 2, 3, 4],
       [1, 2, 0, 4]])

In [ ]:
np.linalg.det(m)

-12.0

In [ ]:
#19 INV Calculates the inverse of a matrix.
np.linalg.inv(m)

array([[ 1.5       ,  2.        , -1.83333333, -1.16666667],
       [ 1.25      ,  1.        , -1.08333333, -0.91666667],
       [-1.5       , -2.        ,  2.16666667,  0.83333333],
       [-1.        , -1.        ,  1.        ,  1.        ]])

In [ ]:
#20 Matmul matrix multiplication
a=([[1,2],[3,5]])
b=([[3,4],[3,1]])
np.matmul(a,b)

array([[ 9,  6],
       [24, 17]])